/*
 *  objc_scanner_actions.h
 *  Codon
 *
 *  Created by Brent Gulanowski on 11/17/07.
 *  Copyright 2007 Bored Astronaut Software. All rights reserved.
 *
 */


#include "objc_parser.h" // file generated by Bison including type symbols

void count();

/*
 The scan... functions create tokens which are stored in yylval.
 
 The pure C parser will ignore comments and white space but will fail with an error when it encounters a cpp macro.
 
 The Objective-C Parser framework will handle comments, whitespace and macros without the aid of the generated parser.
 */

extern void scanMacro();

extern void scanCommentBlock();
extern void scanCommentLine();
extern void scanWhiteSpace();

extern int scanConstant( char *tokenString );    // CONSTANT
extern int scanCString( char *tokenString );     // STRING_LITERAL
extern int scanObjCString( char *tokenString );  // OBJC_STRING_LITERAL

/*
 An identifier is stored in a context table as a specialized type determined by the parser, and retrieved on subsequent occurrences
 */
extern int scanType( char *tokenString );        // IDENTIFIER->TYPE_NAME/CLASS_NAME/PROTOCOL_NAME/CATEGORY_NAME
